server:
  port: 80
---
spring:
  application:
    name: dubbo-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://121.40.230.136:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: MISAKIRINNE
    password: misaki123

---
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: club.fallngsakura.springcloud.entities

---
dubbo:
  ##暴露的服务名称
  application:
    name: ${spring.application.name}
  ##配置注册中心
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  ##配置通信协议
  protocol:
    name: dubbo
    port: -1  #随机端口